dictionaries = ["en_gb"]

ignore_paths = ["all_fr.md"]

words = [
	"Gryffindor", "Godric", "Gryffindors",
	"Slytherin", "Salazar", "Slytherins",
	"Ravenclaw", "Rowena", "Ravenclaws",
	"Hufflepuff", "Helga", "Hufflepuffs",
	"Tsesarevitch", "Vladmir", "Kemenov", "Katya",
	"Vassili", "Vassilievitch", "Kemenovs", "Kemenov's",
	"Theodore", "Nott", "Theo", "Notts",
	"Neville", "Longbottom", "Longbottoms",
	"Mione", "Hermione", "Granger", "Grangers",
	"Draco", "Malfoy", "Lucius", "Malfoys", "Malfoy's",
	"Lovegood", "Luna", "Xenophilius", "Amiphilius", "Leonis",
	"Lovegoods",
	"Selwyn", "Selwyns",
	"Entwhistle", "Wyllt", "Myrddin", "Entwhistles", "Wyllts",
	"Leonara",
	"Cho", "Chang",
	"Weasley", "Weasleys",
	"Greengrass",
	"wizarding",
	"Portkey",
	"Wrackspurt", "Wrackspursts",
	"Pomfrey",
	"Mediwitch", "Mediwizard", "Medimagic",
	"Mediwitches", "Mediwizards",
	"Auror", "Aurors",
	"Albus", "Dumbledore",
	"Gellert", "Grindelwald",
	"Bellatrix", "Rodolphus", "Lestrange",
	"Sasssly",
	"Amos", "Cedric", "Diggory",
	"Bagman",
	"Durmstrang", "Beauxbâtons",
]
